name: Build Android

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Rust target
        run: rustup target add aarch64-linux-android

      - name: Setup Android NDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.2.12479018"

      - name: Build Android ARM64
        shell: bash
        run: |
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk/27.2.12479018"
          export PATH="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH"

          export CC_aarch64_linux_android=aarch64-linux-android24-clang
          export CXX_aarch64_linux_android=aarch64-linux-android24-clang++

          cargo build --release \
            --target aarch64-linux-android

      - name: Rename binary
        run: |
          mv target/aarch64-linux-android/release/grail \
             target/aarch64-linux-android/release/grail-arm64-android

      - name: Upload Android binary
        uses: actions/upload-artifact@v4
        with:
          name: grail-android-arm64
          path: target/aarch64-linux-android/release/grail-arm64-android
